[package]
name = "containers"
version = "0.4.0"
authors = ["M Farkas-Dyck <strake888@gmail.com>"]
description = "Containers"
license = "MIT OR Apache-2.0"
repository = "https://github.com/strake/libreal.rs"
documentation = "https://docs.rs/containers/"

[dependencies]
heap = "0.1"
rel = "0.1"
typenum = { version = "1.2", features = ["no_std"] }

[dev-dependencies]
quickcheck = "0.4"
quickcheck_macros = "0.4"
