[package]
name = "containers"
version = "0.1.1"
authors = ["M Farkas-Dyck <strake888@gmail.com>"]
description = "Containers"
license = "MIT OR Apache-2.0"

[dependencies]
rel = "0.1"
typenum = { version = "1.2", features = ["no_std"] }

[dev-dependencies]
quickcheck = "0.2"
quickcheck_macros = "0.2"
